- hosts: server
  become: true
  tasks:
    - name: INSTALL EPEL REPO PACKAGE FROM STANDARD REPO
      yum:
        name: epel-release    
        state: present

    - name: INSTALL OPENVPN AND UTILS
      yum:
        name: 
          - openvpn
          - easy-rsa
          - mc
        state: present

    - name: COPY server.conf 
      copy:
        src: server/server.conf
        dest: /etc/openvpn/server.conf

    - name: COPY iroute FILE
      copy:
        src: server/client
        dest: /etc/openvpn/client/

    - name: COPY prepeare_server.sh
      copy:
        src: files/server/prepeare_server.sh
        dest: /etc/openvpn/prepeare_server.sh
        mode: '0760'
